# Java Maven CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      # only integration tests
      #- run: mvn integration-test
      # run all tests
      - run: mvn verify

      - store_artifacts:
          path:  target

      # upload report to code cov (xml is supported)
      # https://github.com/codecov/example-java
      # Change Organization Settings -> Security to avoid orbs permission error
      - codecov/upload:
          file: target/my-reports/jacoco.xml
          token: 0e20cd12-4df6-4d58-a62d-ae5ee371c099
