version: 2.1

  docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
    - image: circleci/postgres:12-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: circle_test

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
