version: '3.1'

services:

  movies-mysql:
    image: mysql:8.0.18
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=potatoe
      - MYSQL_DATABASE=movies
      - MYSQL_USER=falcon
      - MYSQL_PASSWORD=potatoe2
    ports:
      - 3306:3306

    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp