global:
  scrape_interval: 15s  # How often to scrape targets (default is 1m)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'movies-app'
    metrics_path: '/actuator/prometheus'  # Spring Boot Actuator metrics
    static_configs:
    # Use host.docker.internal for Windows/macOS to connect to the current machine
      - targets: ['host.docker.internal:8080']
    # On Linux, replace 'host.docker.internal' with the machine's IP (e.g., 192.168.1.100:8080)

#  - job_name: 'docker'
#    static_configs:
#      - targets: ['cadvisor:8080']  # If monitoring Docker containers with cAdvisor
